spring:
  application:
    name: dubbo-provider-sample
  profiles:
    active: local
dubbo:
  registry:
    address: nacos://172.16.19.233:30829
    simplified: true
  protocol:
      name: dubbo
      port: -1
  scan:
    base-packages: io.github.sunny.dubbo.service
  metadata-report:
    address: nacos://172.16.19.233:30829
  provider:
    timeout: 5000