spring:
  application:
    name: dubbo-consumer-sample
  profiles:
    active: local

dubbo:
  registry:
    address: nacos://172.16.19.233:30829
    register: true
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false
  scan:
    base-packages: io.github.sunny.dubbo.controller
  metadata-report:
    address: nacos://172.16.19.233:30829
server:
  port: 8811